#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
#This allows HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html
rm /etc/nginx/sites-enabled/default
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
