#!/usr/bin/env bash
#


#Update pakage list
sudo apt-get update
#install Nginx
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html



service nginx start
