#!/usr/bin/env bash
#short version of the bach script that configures an Nginx server to listen to the port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart 
pkill -o nginx